steps:
  # Install dependencies
  - name: "node:18"
    entrypoint: npm
    args: ["ci"]

  # Run tests
  - name: "node:18"
    entrypoint: npm
    args: ["test"]

  # Run linting
  - name: "node:18"
    entrypoint: npm
    args: ["run", "lint"]

  # Build
  - name: "node:18"
    entrypoint: npm
    args: ["run", "build"]

  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/auth-rbac-api:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/auth-rbac-api:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "auth-rbac-api"
      - "--image=gcr.io/$PROJECT_ID/auth-rbac-api:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/auth-rbac-api:$COMMIT_SHA"
